# Generated by Django 4.2.16 on 2024-11-10 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentconfirmation',
            name='transaction_id',
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
    ]
